"""Q Operator Prototype v0.1 -- frozen wording.

Do not edit this file without minting a new version (v0.2+) and re-running the
full-field + tournament experiments against the new wording. See
notes/q-operator-prototype-v0.1.md for the versioning record and evidence base.
This module exists so every consumer (CLI scripts, the local reader app) reads
the exact same criterion text from one place instead of hand-copied constants.
"""
from __future__ import annotations

VERSION = "v0.1"

CRITERIA: dict[str, str] = {
    "ECHO": (
        "Select the passage that most strongly returns to, mirrors, resonates with, or "
        "meaningfully recurs from the source passage. Choose NONE if no candidate offers "
        "a meaningful echo."
    ),
    "DEVELOP": (
        "Select the passage that most productively extends, complicates, develops, or "
        "transforms what the source passage is doing. Choose NONE if no candidate offers "
        "a productive development."
    ),
    "CONTRADICT": (
        "Select the passage that most meaningfully resists, reverses, destabilizes, "
        "challenges, or creates tension with the source passage. Choose NONE if no "
        "candidate creates meaningful tension."
    ),
    "BRIDGE": (
        "Select the passage that creates the strongest useful connection to the source "
        "that is not primarily based on obvious surface similarity, repeated wording, or "
        "direct thematic overlap. Choose NONE if no candidate offers such a connection."
    ),
}

OPERATOR_NAMES = list(CRITERIA)  # ["ECHO", "DEVELOP", "CONTRADICT", "BRIDGE"]
